import type { SourceDefinition } from '../domain/catalog/types';

export const SOURCE_DEFINITIONS: SourceDefinition[] = [
  {
    id: 'fitgirl',
    name: 'FitGirl Repacks',
    baseUrl: 'https://fitgirl-repacks.site',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'dodi',
    name: 'DODI Repacks',
    baseUrl: 'https://dodi-repacks.site',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'steamrip',
    name: 'SteamRIP',
    baseUrl: 'https://steamrip.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'onlinefix',
    name: 'Online-Fix',
    baseUrl: 'https://online-fix.me',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'goggames',
    name: 'GOG Games',
    baseUrl: 'https://gog-games.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'xatab',
    name: 'Xatab Repack',
    baseUrl: 'https://xatab-repack.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'repack-games',
    name: 'Repack Games',
    baseUrl: 'https://repack-games.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'repacklab',
    name: 'RepackLab',
    baseUrl: 'https://repacklab.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'elamigos',
    name: 'ElAmigos Games',
    baseUrl: 'https://www.elamigosgamez.net',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: '.col-lg-2.col-md-3.col-sm-5.portfolio-item .card',
      title: 'h6.card-title a',
      link: 'h6.card-title a',
      size: '.text-body-secondary',
      description: 'small',
      image: 'img.card-img-top',
      date: '',
      tags: '',
    },
    downloadLinkSelector:
      "a[href*='mega.nz'], a[href*='drive.google'], a[href*='mediafire'], a[href*='1fichier'], a[href*='uploaded.net']",
    downloadLinkType: 'direct',
    downloadLinkContainer: '.entry-content',
    downloadType: 'direct',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'gload',
    name: 'GLOAD.to',
    baseUrl: 'https://gload.to',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article.game-archive-card',
      title: 'h2.card-title, h3.list-title',
      link: 'a.card-link-wrapper',
      size: '.card-size',
      description: '.card-excerpt',
      image: 'picture img',
      date: '.card-date',
      tags: '.card-genre',
    },
    downloadLinkSelector: "a[href*='magnet:'], a[href*='torrent'], a[href*='upload'], a[href*='mega']",
    downloadLinkType: 'direct',
    downloadLinkContainer: '.entry-content',
    downloadType: 'direct',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'ovagames',
    name: 'Ova Games',
    baseUrl: 'https://www.ovagames.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: '.home-post-wrap',
      title: '.home-post-titles h2 a',
      link: '.home-post-titles h2 a',
      size: '',
      description: '',
      image: 'img.thumbnail',
      date: '',
      tags: '',
    },
    downloadLinkSelector:
      "a[href*='mega.nz'], a[href*='mediafire'], a[href*='drive.google'], a[href*='torrent'], a[href*='magnet:']",
    downloadLinkType: 'direct',
    downloadLinkContainer: '.entry-content',
    downloadType: 'direct',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
];
