import type { SourceDefinition } from '../domain/catalog/types';

export const SOURCE_DEFINITIONS_PART1: SourceDefinition[] = [
  {
    id: 'fitgirl',
    name: 'FitGirl Repacks',
    baseUrl: 'https://fitgirl-repacks.site',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'dodi',
    name: 'DODI Repacks',
    baseUrl: 'https://dodi-repacks.site',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'steamrip',
    name: 'SteamRIP',
    baseUrl: 'https://steamrip.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'onlinefix',
    name: 'Online-Fix',
    baseUrl: 'https://online-fix.me',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'goggames',
    name: 'GOG Games',
    baseUrl: 'https://gog-games.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'xatab',
    name: 'Xatab Repack',
    baseUrl: 'https://xatab-repack.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
];
