import type { SourceDefinition } from '../domain/catalog/types';

export const SOURCE_DEFINITIONS_PART3: SourceDefinition[] = [
  {
    id: 'mercs213',
    name: 'MERC$213',
    baseUrl: 'https://mercs213.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: '.game-card, .post-item',
      title: 'h2 a, h3 a',
      link: 'h2 a, h3 a',
      size: '.file-size, .size',
      description: '.excerpt, .description',
      image: 'img.attachment-thumbnail, img.wp-post-image',
      date: '.date, time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector:
      "a[href*='mega.nz'], a[href*='drive.google'], a[href*='mediafire']",
    downloadLinkType: 'direct',
    downloadLinkContainer: '.entry-content',
    downloadType: 'direct',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'torrminatorr',
    name: 'Torrminatorr',
    baseUrl: 'https://torrminatorr.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'tr',
      title: 'a',
      link: 'a',
      size: 'td',
      description: '',
      image: '',
      date: '',
      tags: '',
    },
    downloadLinkSelector: "a[href*='torrent'], a[href*='magnet:']",
    downloadLinkType: 'torrent',
    downloadLinkContainer: '.post-body, .entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'gamecopyworld',
    name: 'GameCopyWorld',
    baseUrl: 'https://gamecopyworld.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'table tr',
      title: 'td a',
      link: 'td a',
      size: 'td:last-child',
      description: '',
      image: 'img',
      date: '',
      tags: '',
    },
    downloadLinkSelector:
      "a[href*='mega.nz'], a[href*='drive.google'], a[href*='mediafire'], a[href*='uploaded']",
    downloadLinkType: 'direct',
    downloadLinkContainer: '.tabcontent, .content',
    downloadType: 'direct',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'tinrepacks',
    name: 'Tiny Repacks',
    baseUrl: 'https://tiny-repacks.win',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article, .post',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'tapochek',
    name: 'Tapochek',
    baseUrl: 'https://tapochek.net',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'tr',
      title: 'a',
      link: 'a',
      size: 'td',
      description: '',
      image: '',
      date: '',
      tags: '',
    },
    downloadLinkSelector: "a[href*='torrent'], a[href*='magnet:']",
    downloadLinkType: 'torrent',
    downloadLinkContainer: '.postbody, .entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'rgmechanics',
    name: 'RG Mechanics',
    baseUrl: 'https://rg-mechanics.org',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size'), p:contains('Размер')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector:
      "a[href*='magnet:'], a[href*='torrent'], a[href*='mega.nz'], a[href*='drive.google']",
    downloadLinkType: 'direct',
    downloadLinkContainer: '.entry-content',
    downloadType: 'direct',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
];
