import type { SourceDefinition } from '../domain/catalog/types';

export const SOURCE_DEFINITIONS_PART4: SourceDefinition[] = [
  {
    id: 'chovka',
    name: 'Chovka',
    baseUrl: 'https://chovka.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: '.post-entry, article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector:
      "a[href*='mega.nz'], a[href*='drive.google'], a[href*='mediafire']",
    downloadLinkType: 'direct',
    downloadLinkContainer: '.entry-content',
    downloadType: 'direct',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'blackbox',
    name: 'BlackBox Repack',
    baseUrl: 'https://blackboxrepack.com',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: '.game-box, article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
  {
    id: 'scooter',
    name: 'Scooter Repacks',
    baseUrl: 'https://scooter-repacks.site',
    mirrors: [],
    scrapeType: 'html',
    selectors: {
      gameContainer: 'article',
      title: 'h1 a, h2 a',
      link: 'h1 a, h2 a',
      size: "p:contains('Size')",
      description: 'p:not(:has(a))',
      image: 'img',
      date: 'time',
      tags: 'a[rel=tag]',
    },
    downloadLinkSelector: "a[href*='magnet:']",
    downloadLinkType: 'magnet',
    downloadLinkContainer: '.entry-content',
    downloadType: 'torrent',
    updateIntervalMinutes: 360,
    enabled: true,
  } as const satisfies SourceDefinition,
];
